// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQS2RxoRJR0HcJYhucjXUoXNz6iRuT4gk',
    appId: '1:1021400245597:web:6e230b50e5fd24450d34b4',
    messagingSenderId: '1021400245597',
    projectId: 'makbul-app',
    authDomain: 'makbul-app.firebaseapp.com',
    storageBucket: 'makbul-app.firebasestorage.app',
    measurementId: 'G-EMD0HXRFB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcdw8Qes72ookEvdWxRcfzBfE8BkjXBHY',
    appId: '1:1021400245597:android:d344cc8171a5229e0d34b4',
    messagingSenderId: '1021400245597',
    projectId: 'makbul-app',
    storageBucket: 'makbul-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlKzN85Qxt67TeU9Q_Q_Z0pDu1oE_tSKc',
    appId: '1:1021400245597:ios:ea7526bfa545b4df0d34b4',
    messagingSenderId: '1021400245597',
    projectId: 'makbul-app',
    storageBucket: 'makbul-app.firebasestorage.app',
    iosBundleId: 'com.example.makbulApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlKzN85Qxt67TeU9Q_Q_Z0pDu1oE_tSKc',
    appId: '1:1021400245597:ios:ea7526bfa545b4df0d34b4',
    messagingSenderId: '1021400245597',
    projectId: 'makbul-app',
    storageBucket: 'makbul-app.firebasestorage.app',
    iosBundleId: 'com.example.makbulApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQS2RxoRJR0HcJYhucjXUoXNz6iRuT4gk',
    appId: '1:1021400245597:web:3d5a7405675624ad0d34b4',
    messagingSenderId: '1021400245597',
    projectId: 'makbul-app',
    authDomain: 'makbul-app.firebaseapp.com',
    storageBucket: 'makbul-app.firebasestorage.app',
    measurementId: 'G-ZF9BRD8QYZ',
  );
}
